project:
  type: website

website:
  title: "R-Ladies Baltimore"
  navbar:
    right:
      - href: https://www.meetup.com/rladies-baltimore
        text: Events
      - blog.qmd
      - coc.qmd
      - icon: github
        href: https://github.com/rladies-baltimore
      - icon: twitter
        href: https://twitter.com/RLadiesBmore

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

execute:
  freeze: auto



