---
title: "Code of Conduct"
format:
    html:
        toc: true
        toc-depth: 3
---


The leadership, mentoring & teaching roles within this Community are held exclusively by minority genders (majority gender speakers may be allowed/invited as one-off guests in exceptional circumstances at the leadership team's discretion). Due to unexpected demand, we have opened learning participation to all genders, dependent on initial and on-going vetting by the leadership team. However, the stated priority of the R-Ladies communities is the development & support specifically of those identifying as a minority gender, and we, therefore, reserve the right to guard this interest through whatever measures the leadership team deems appropriate. Anyone involved with R-Ladies Baltimore is expected to fully respect each other, the mandate of this community, and the goodwill on which R-Ladies is founded, or face expulsion/a penalty of any form, at the discretion of the leadership team.

Full community guidelines are found here: [rladies/starter-kit/wiki](https://github.com/rladies/starter-kit/wiki).

## Photos, Films and all other media/recordings:

Photos, Films, and all other media/recordings: photographs and/or video/other media will be taken at events held by this community. By taking part in an R-Ladies Baltimore event you grant the community organizers full rights to use the images resulting from the photography/video filming/media, and any reproductions or adaptations of the images for publicity, fundraising or other purposes to help achieve the community’s aims. This might include (but is not limited to), the right to use them in their printed and online publicity, social media, press releases and funding applications. If you do not wish to be recorded in these media please inform a community organizer.

